item {
    id: 2
    name: 'Plastic'
}

item {
    id: 3
    name: 'Net'
}

item {
    id: 5
    name: 'Straw'
}

item {
    id: 7
    name: 'Tray'
}

item {
    id: 9
    name: 'Can'
}

item {
    id: 10
    name: 'Glass'
}

item {
    id: 11
    name: 'Dolphin'
}


 
 
 
  
 
  
